import { defineCreationSuite } from '../support/savingsCreationSuite';

/**
 * Normal Savings Account - 1001 — Minor account, full cold creation through real final submit.
 * Story: user-stories/US_009_*.md · Plan: specs/NORMAL_TS001-test-plan.md
 *
 * Per-step (Staff-shaped) journey generated by defineCreationSuite. Human-assisted
 * (OTP + DigiLocker + liveliness), so it skips in CI. PII-free: applicant data is synthetic;
 * the introducer name, CBS account and staff code come from env vars.
 */
defineCreationSuite({
    suiteId: 'NORMAL_TS001',
    scheme: 'normal',
    accountType: 'minor',
    mobileEnv: 'SAHAYOG_NOR_MIN_MOBILE',
    guardianMobileEnv: 'SAHAYOG_NOR_MIN_GUARDIAN_MOBILE',
    minorAadhaarEnv: 'SAHAYOG_NOR_MIN_AADHAAR',
    signalPrefix: '.nor-min',
});
