import { defineCreationSuite } from '../support/savingsCreationSuite';

/**
 * Normal Savings Account - 1001 — Individual account, full cold creation through real final submit.
 * Story: user-stories/US_009_*.md · Plan: specs/NORMAL_TS001-test-plan.md
 *
 * Per-step (Staff-shaped) journey generated by defineCreationSuite. Human-assisted
 * (OTP + DigiLocker + liveliness), so it skips in CI. PII-free: applicant data is synthetic;
 * the introducer name, CBS account and staff code come from env vars.
 */
defineCreationSuite({
    suiteId: 'NORMAL_TS001',
    scheme: 'normal',
    accountType: 'individual',
    mobileEnv: 'SAHAYOG_NOR_IND_MOBILE',
    signalPrefix: '.nor-ind',
});
