import { defineCreationSuite } from '../support/savingsCreationSuite';

/**
 * Silver Savings Account - 1002 — Joint account, full cold creation through real final submit.
 * Story: user-stories/US_008_*.md · Plan: specs/SILVER_TS001-test-plan.md
 *
 * Per-step (Staff-shaped) journey generated by defineCreationSuite. Human-assisted
 * (OTP + DigiLocker + liveliness), so it skips in CI. PII-free: applicant data is synthetic;
 * the introducer name, CBS account and staff code come from env vars.
 */
defineCreationSuite({
    suiteId: 'SILVER_TS001',
    scheme: 'silver',
    accountType: 'joint',
    mobileEnv: 'SAHAYOG_SIL_JNT_MOBILE',
    coMobileEnv: 'SAHAYOG_SIL_JNT_CO_MOBILE',
    signalPrefix: '.sil-jnt',
});
