import { defineCreationSuite } from '../support/savingsCreationSuite';

/**
 * Silver Savings Account - 1002 — Minor account, full cold creation through real final submit.
 * Story: user-stories/US_008_*.md · Plan: specs/SILVER_TS001-test-plan.md
 *
 * Per-step (Staff-shaped) journey generated by defineCreationSuite. Human-assisted
 * (OTP + DigiLocker + liveliness), so it skips in CI. PII-free: applicant data is synthetic;
 * the introducer name, CBS account and staff code come from env vars.
 */
defineCreationSuite({
    suiteId: 'SILVER_TS001',
    scheme: 'silver',
    accountType: 'minor',
    mobileEnv: 'SAHAYOG_SIL_MIN_MOBILE',
    guardianMobileEnv: 'SAHAYOG_SIL_MIN_GUARDIAN_MOBILE',
    minorAadhaarEnv: 'SAHAYOG_SIL_MIN_AADHAAR',
    signalPrefix: '.sil-min',
});
